services:
  mindcraft:
    build: .
    environment:
      SETTINGS_JSON: |
        {"auto_open_ui": false}
    volumes:
      - ./settings.js:/app/settings.js
      - ./keys.json:/app/keys.json
      - ./profiles:/app/profiles
      - ./bots:/app/bots
    ports:
      - "3000-3003:3000-3003" # see the view from the camera mounted on your bot head: http://localhost:3000/
      - 8080 # Mindserver port
    extra_hosts:
    - "host.docker.internal:host-gateway"

  viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy
    stdin_open: true
    tty: true
